### PR TITLE
Gettransaction

### PR DESCRIPTION
**Pull request by sfalpha**
I add getTransactionByInvoice and getTransactionDetailByInvoice for checking
transaction status after complete paynow request.

It really necessary to check status in case callback request has problems
but currently not implemented.

### CODE REVIEW

**Comment by jon-paysbuy** [comment]
Thanks for this. There appears to be a typo in the class name though - "PaysbuyGetTrasaction"

**Comment by sfalpha** [comment]
Ok I will fix the typo one.

**Comment by jon-paysbuy** [comment]
Hi there - did you fix it?

**Comment by jon-paysbuy** [comment]
I'll merge it in and fix it 😄

**Pull request merged**
